### ISSUE TITLE
Visible canvas element

### ISSUE THREAD

**Issue by God-damnit-all** [andryou/scriptsafe#405]
ScriptSafe, for whatever reason, has a potentially visible canvas element when you reload pages and it can really mess with where chromium thinks the page should be scrolled to.

Personally, I fix it with this CSS in Stylus:
```css
canvas[class^="scriptsafe_"], canvas[class*=" scriptsafe_"] { display: none }
```

However, simply making sure that these elements have `style="display:none"` included in their canvas tags would fix this issue for everyone.
